[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2021"
authors = ["Shivank Kapur <shivank@routerprotocol.com>"]
description = "Basic implementation of a user defined bridge contract"
repository = "https://github.com/router-protocol/cw-bridge-contracts.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instanti`ate/execute/query exports
library = []

[dependencies]
cosmwasm-std = { version = "1.0.0", features = ["staking"] }
cw-storage-plus = { version = "0.13.4" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.23" }
cw20 = { version = "0.13.4" }
cw20-base = { version = "0.13.4", features = ["library"] }
cw0 = { version = "0.10.3" }
cw2 = { version = "0.13.4" }
cosmwasm-crypto = "1.0.0"
hex = "0.4"
arrayref = "0.3.6"
codec = { package = "parity-scale-codec", version = "2.0.0", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }
base64 = "0.13.0"

[dev-dependencies]
cosmwasm-schema = { version = "0.16.0" }
